#!/usr/bin/env python3
"""Kartu hasil scan VirusTotal (PNG) untuk landing page — dipakai oleh CI build.yml.

Dulu screenshot di-recapture manual dan selalu ketinggalan satu versi 😅.
Sekarang CI yang gambar ulang tiap rilis: hasil scan, SHA-256, tanggal.

Pakai:
    python3 make-vt-card.py --out docs/images/virustotal-report.png \
        --data docs/data/virustotal.json

Butuh Pillow (CI: `pip install --quiet pillow`).
"""
import argparse
import json
from datetime import date

from PIL import Image, ImageDraw, ImageFont

BG = (15, 17, 21)
SURFACE = (23, 26, 33)
OUTLINE = (44, 49, 59)
BRAND = (255, 176, 32)
TEXT = (236, 239, 244)
DIM = (155, 163, 175)
OK = (61, 220, 132)
DENY = (255, 92, 92)


def font(size, mono=False):
    try:
        return ImageFont.load_default(size=size)
    except TypeError:  # pillow lama
        return ImageFont.load_default()


def wrap(draw, text, f, max_w):
    words, lines, cur = text.split(), [], ""
    for w in words:
        trial = (cur + " " + w).strip()
        if draw.textlength(trial, font=f) <= max_w:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="docs/data/virustotal.json")
    ap.add_argument("--out", default="docs/images/virustotal-report.png")
    args = ap.parse_args()

    d = json.load(open(args.data))
    vt = d.get("virustotal", {})
    checked = vt.get("checked", False)
    det, tot = vt.get("detected", 0), vt.get("total", 72)
    clean = checked and det == 0
    color = OK if clean else (DENY if checked else BRAND)
    # FONT: pakai ASCII murni untuk pemisah — load_default() tidak punya glyh "·" "—".
    status = (
        f"{det} / {tot} - 100% CLEAN - NO SECURITY VENDORS FLAGGED THIS FILE"
        if clean
        else ("HASIL SCAN BELUM TERSEDIA (VT_API_KEY belum diset)" if not checked else f"{det} vendor menandai file - periksa permalink")
    )

    W, H = 1400, 820
    img = Image.new("RGB", (W, H), BG)
    dr = ImageDraw.Draw(img)

    # header
    dr.rounded_rectangle([40, 40, W - 40, 150], 20, fill=SURFACE, outline=OUTLINE, width=2)
    dr.ellipse([70, 70, 120, 120], fill=BRAND)
    dr.text((140, 72), "AppsPerms", font=font(44), fill=TEXT)
    dr.text((420, 86), f"v{d.get('version', '?')} - Audit VirusTotal (kartu otomatis CI)", font=font(24), fill=DIM)
    upd = str(d.get("updated_utc", "")).replace("T", " ").replace("Z", " UTC")
    dr.text((W - 60 - dr.textlength(upd, font=font(22)), 90), upd, font=font(22), fill=DIM)

    # ringkasan besar
    dr.rounded_rectangle([40, 180, W - 40, 430], 24, fill=SURFACE, outline=OUTLINE, width=2)
    dr.text((90, 240), f"{det} / {tot}" if checked else "- / -", font=font(112), fill=color)
    for i, line in enumerate(wrap(dr, status, font(28), W - 660 - 40)):
        dr.text((600, 232 + i * 36), line, font=font(28), fill=TEXT)
    permalink = vt.get("permalink", "https://www.virustotal.com/gui/home/upload")
    for i in range(0, len(permalink), 62):  # hash panjang: potong per karakter, jangan overflow
        dr.text((600, 318 + (i // 62) * 30), permalink[i:i + 62], font=font(20), fill=DIM)

    # metadata file
    rel = d.get("release", {})
    dr.rounded_rectangle([40, 460, W - 40, 770], 24, fill=SURFACE, outline=OUTLINE, width=2)
    rows = [
        ("File", str(rel.get("file", "?"))),
        ("Ukuran", f"{rel.get('size_mb', '?')} MB"),
        ("SHA-256", str(rel.get("sha256", "?"))),
        ("Cara cek ulang", "Buka permalink di atas, atau unggah file APK-mu ke virustotal.com/gui/home/upload - hash harus sama persis."),
    ]
    y = 500
    for label, val in rows:
        dr.text((80, y), label.upper(), font=font(20), fill=DIM)
        for i, line in enumerate(wrap(dr, str(val), font(26), W - 480)):
            dr.text((330, y if i == 0 else y + 34), line, font=font(26), fill=TEXT)
        y += 34 * max(1, len(wrap(dr, str(val), font(26), W - 480))) + 22

    dr.text((40, H - 36), f"Generated by AppsPerms CI - {date.today().isoformat()} - Built in XyVerse", font=font(20), fill=DIM)
    img.save(args.out)
    print(f"kartu VT ditulis: {args.out}")


if __name__ == "__main__":
    main()
